/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    devices: DeviceAuthOperations;
    integrations: IntegrationAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    programs: Program;
    schedule: Schedule;
    departments: Department;
    folders: Folder;
    users: User;
    devices: Device;
    integrations: Integration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Device | Integration;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface DeviceAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface IntegrationAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Name shown on screens for this media item.
   */
  name?: string | null;
  folder?: (number | null) | Folder;
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    fullHD?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: number;
  name: string;
  /**
   * Parent folder. Leave empty to create a top-level folder.
   */
  parent?: (number | null) | Folder;
  /**
   * Which collection this folder belongs to.
   */
  type: 'media' | 'programs';
  department?: (number | null) | Department;
  /**
   * Sort order within sibling folders (lower = first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  /**
   * Brief overview for other users.
   */
  description?: string | null;
  slides?:
    | (
        | {
            image: number | Media;
            transition?: ('fade' | 'cut' | 'slide') | null;
            /**
             * How should the player move to the next slide?
             */
            advanceMode: 'timed' | 'manual';
            duration?: number | null;
            /**
             * Move this slide to another segment or the top level on save.
             */
            _moveToSegment?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            video: number | Media;
            transition?: ('fade' | 'cut' | 'slide') | null;
            /**
             * How should the player move to the next slide?
             */
            advanceMode: 'timed' | 'manual' | 'onEnd';
            duration?: number | null;
            /**
             * Repeats the video until the slide transitions.
             */
            loop?: boolean | null;
            /**
             * Move this slide to another segment or the top level on save.
             */
            _moveToSegment?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
        | {
            /**
             * Paste a YouTube link (e.g. youtube.com/watch?v=...) or just the video ID.
             */
            youtubeId: string;
            videoTitle?: string | null;
            transition?: ('fade' | 'cut' | 'slide') | null;
            /**
             * How should the player move to the next slide?
             */
            advanceMode: 'timed' | 'manual' | 'onEnd';
            duration?: number | null;
            /**
             * Repeats the video until the slide transitions.
             */
            loop?: boolean | null;
            /**
             * Move this slide to another segment or the top level on save.
             */
            _moveToSegment?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'youtubeBlock';
          }
        | {
            audio: number | Media;
            transition?: ('fade' | 'cut' | 'slide') | null;
            /**
             * How should the player move to the next slide?
             */
            advanceMode: 'timed' | 'manual' | 'onEnd';
            duration?: number | null;
            /**
             * Repeats the video until the slide transitions.
             */
            loop?: boolean | null;
            /**
             * Move this slide to another segment or the top level on save.
             */
            _moveToSegment?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'audioBlock';
          }
        | {
            transition?: ('fade' | 'cut' | 'slide') | null;
            /**
             * How should the player move to the next slide?
             */
            advanceMode: 'timed' | 'manual';
            duration?: number | null;
            /**
             * Move this slide to another segment or the top level on save.
             */
            _moveToSegment?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blackScreenBlock';
          }
        | {
            /**
             * For identification in the admin UI only.
             */
            name?: string | null;
            /**
             * Audio that plays across all slides in this segment.
             */
            backgroundAudio?: (number | null) | Media;
            /**
             * When enabled, the segment restarts from slide 1 after the last slide.
             */
            loop?: boolean | null;
            /**
             * How the player moves to the next item after this segment ends.
             */
            advanceMode?: ('slides' | 'timed' | 'manual') | null;
            /**
             * Play this segment for this many minutes, then advance.
             */
            duration?: number | null;
            /**
             * Slides within this segment.
             */
            slides?:
              | (
                  | {
                      image: number | Media;
                      transition?: ('fade' | 'cut' | 'slide') | null;
                      /**
                       * How should the player move to the next slide?
                       */
                      advanceMode: 'timed' | 'manual';
                      duration?: number | null;
                      /**
                       * Move this slide to another segment or the top level on save.
                       */
                      _moveToSegment?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'imageBlock';
                    }
                  | {
                      video: number | Media;
                      transition?: ('fade' | 'cut' | 'slide') | null;
                      /**
                       * How should the player move to the next slide?
                       */
                      advanceMode: 'timed' | 'manual' | 'onEnd';
                      duration?: number | null;
                      /**
                       * Repeats the video until the slide transitions.
                       */
                      loop?: boolean | null;
                      /**
                       * Move this slide to another segment or the top level on save.
                       */
                      _moveToSegment?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'videoBlock';
                    }
                  | {
                      /**
                       * Paste a YouTube link (e.g. youtube.com/watch?v=...) or just the video ID.
                       */
                      youtubeId: string;
                      videoTitle?: string | null;
                      transition?: ('fade' | 'cut' | 'slide') | null;
                      /**
                       * How should the player move to the next slide?
                       */
                      advanceMode: 'timed' | 'manual' | 'onEnd';
                      duration?: number | null;
                      /**
                       * Repeats the video until the slide transitions.
                       */
                      loop?: boolean | null;
                      /**
                       * Move this slide to another segment or the top level on save.
                       */
                      _moveToSegment?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'youtubeBlock';
                    }
                  | {
                      audio: number | Media;
                      transition?: ('fade' | 'cut' | 'slide') | null;
                      /**
                       * How should the player move to the next slide?
                       */
                      advanceMode: 'timed' | 'manual' | 'onEnd';
                      duration?: number | null;
                      /**
                       * Repeats the video until the slide transitions.
                       */
                      loop?: boolean | null;
                      /**
                       * Move this slide to another segment or the top level on save.
                       */
                      _moveToSegment?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'audioBlock';
                    }
                  | {
                      transition?: ('fade' | 'cut' | 'slide') | null;
                      /**
                       * How should the player move to the next slide?
                       */
                      advanceMode: 'timed' | 'manual';
                      duration?: number | null;
                      /**
                       * Move this slide to another segment or the top level on save.
                       */
                      _moveToSegment?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'blackScreenBlock';
                    }
                )[]
              | null;
            /**
             * Drop files here to auto-generate slides inside this segment.
             */
            bulkMedia?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'segmentBlock';
          }
      )[]
    | null;
  folder?: (number | null) | Folder;
  /**
   * Drop files here to auto-generate slides.
   */
  bulkMedia?: (number | Media)[] | null;
  /**
   * When enabled, program loops continuously. When disabled, the program ends after the last slide.
   */
  loop?: boolean | null;
  /**
   * Automatically adds a black screen at the end of the program.
   */
  autoBlackEndSlide?: boolean | null;
  /**
   * Program becomes available for manual selection on this date.
   */
  availableFrom?: string | null;
  /**
   * Leave blank for indefinite availability.
   */
  availableUntil?: string | null;
  /**
   * Devices that can manually select this program.
   */
  availableDevices?: (number | Device)[] | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  name: string;
  deviceType: 'hardware' | 'browser';
  departments: (number | Department)[];
  /**
   * When set, this device mirrors the controlling device's program and slide position.
   */
  controllingDevice?: (number | null) | Device;
  lastHeartbeat?: string | null;
  currentProgram?: (number | null) | Program;
  /**
   * Current slide index, reported by the device.
   */
  currentSlideIndex?: number | null;
  status?: ('online' | 'offline' | 'stale') | null;
  browserToken?: string | null;
  /**
   * Image shown centered on black when no program is running.
   */
  defaultBackground?: (number | null) | Media;
  /**
   * When enabled, the list of available programs is not shown on the device. It will only play auto-scheduled programs.
   */
  hideProgramList?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'devices';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'manager' | 'standard') | null;
  departments?: (number | Department)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  program: number | Program;
  devices: (number | Device)[];
  /**
   * Leave empty for a one-off event on the startTime date. Select days for weekly recurrence.
   */
  daysOfWeek?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  /**
   * The date and time the program starts. For recurring schedules (daysOfWeek set), only the time-of-day is used — the date is ignored.
   */
  startTime: string;
  /**
   * When the program stops. Defaults to 1 hour after startTime.
   */
  endTime?: string | null;
  /**
   * Optional end date for the schedule. Leave blank for indefinite recurrence. Useful for seasonal schedules (e.g., Christmas program ending Dec 25).
   */
  untilDate?: string | null;
  department?: (number | null) | Department;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  /**
   * Descriptive name (e.g. "Home Assistant")
   */
  name: string;
  /**
   * After this date, the API key will stop working.
   */
  expiresAt: string;
  /**
   * Leave empty for access to all departments. Select departments to restrict access.
   */
  departments?: (number | Department)[] | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'integrations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'schedule';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'folders';
        value: number | Folder;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'devices';
        value: number | Device;
      }
    | {
        relationTo: 'integrations';
        value: number | Integration;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'devices';
        value: number | Device;
      }
    | {
        relationTo: 'integrations';
        value: number | Integration;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        fullHD?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slides?:
    | T
    | {
        imageBlock?:
          | T
          | {
              image?: T;
              transition?: T;
              advanceMode?: T;
              duration?: T;
              _moveToSegment?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              video?: T;
              transition?: T;
              advanceMode?: T;
              duration?: T;
              loop?: T;
              _moveToSegment?: T;
              id?: T;
              blockName?: T;
            };
        youtubeBlock?:
          | T
          | {
              youtubeId?: T;
              videoTitle?: T;
              transition?: T;
              advanceMode?: T;
              duration?: T;
              loop?: T;
              _moveToSegment?: T;
              id?: T;
              blockName?: T;
            };
        audioBlock?:
          | T
          | {
              audio?: T;
              transition?: T;
              advanceMode?: T;
              duration?: T;
              loop?: T;
              _moveToSegment?: T;
              id?: T;
              blockName?: T;
            };
        blackScreenBlock?:
          | T
          | {
              transition?: T;
              advanceMode?: T;
              duration?: T;
              _moveToSegment?: T;
              id?: T;
              blockName?: T;
            };
        segmentBlock?:
          | T
          | {
              name?: T;
              backgroundAudio?: T;
              loop?: T;
              advanceMode?: T;
              duration?: T;
              slides?:
                | T
                | {
                    imageBlock?:
                      | T
                      | {
                          image?: T;
                          transition?: T;
                          advanceMode?: T;
                          duration?: T;
                          _moveToSegment?: T;
                          id?: T;
                          blockName?: T;
                        };
                    videoBlock?:
                      | T
                      | {
                          video?: T;
                          transition?: T;
                          advanceMode?: T;
                          duration?: T;
                          loop?: T;
                          _moveToSegment?: T;
                          id?: T;
                          blockName?: T;
                        };
                    youtubeBlock?:
                      | T
                      | {
                          youtubeId?: T;
                          videoTitle?: T;
                          transition?: T;
                          advanceMode?: T;
                          duration?: T;
                          loop?: T;
                          _moveToSegment?: T;
                          id?: T;
                          blockName?: T;
                        };
                    audioBlock?:
                      | T
                      | {
                          audio?: T;
                          transition?: T;
                          advanceMode?: T;
                          duration?: T;
                          loop?: T;
                          _moveToSegment?: T;
                          id?: T;
                          blockName?: T;
                        };
                    blackScreenBlock?:
                      | T
                      | {
                          transition?: T;
                          advanceMode?: T;
                          duration?: T;
                          _moveToSegment?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              bulkMedia?: T;
              id?: T;
              blockName?: T;
            };
      };
  folder?: T;
  bulkMedia?: T;
  loop?: T;
  autoBlackEndSlide?: T;
  availableFrom?: T;
  availableUntil?: T;
  availableDevices?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  program?: T;
  devices?: T;
  daysOfWeek?: T;
  startTime?: T;
  endTime?: T;
  untilDate?: T;
  department?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  type?: T;
  department?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  departments?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  name?: T;
  deviceType?: T;
  departments?: T;
  controllingDevice?: T;
  lastHeartbeat?: T;
  currentProgram?: T;
  currentSlideIndex?: T;
  status?: T;
  browserToken?: T;
  defaultBackground?: T;
  hideProgramList?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  name?: T;
  expiresAt?: T;
  departments?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}